# Worfklow for https://jmfayard.github.io/refreshVersions/

name: RefreshVersions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  "Refresh-Versions":
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@v3
        with:
          ref: main

      - name: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create google-services.json file
        run: cat /home/runner/work/newquiz/newquiz/app/google-services.json | base64

      - name: Put google-services.json data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/newquiz/newquiz/app/google-services.json

      - name: create-branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        with:
          branch: dependency-update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: gradle refreshVersions
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: refreshVersions

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: noreply@github.com
          message: Refresh versions.properties
          new_branch: dependency-update
          push: --force --set-upstream origin dependency-update

      - name: Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: dependency-update
          destination_branch: main
          pr_title: Upgrade gradle dependencies
          pr_body: '[refreshVersions](https://github.com/jmfayard/refreshVersions) has found those library updates!'
          pr_draft: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
